name: Build & Test

on:
  push:
  schedule:
  - cron:  '0 3 * * 1'


jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update -n base -f environment.yml
        pip install . --no-deps
    - name: Test with pytest
      run: |
        conda install pytest
        pytest test
